### ISSUE TITLE
Pulling peering-manager-worker - Not found?

### ISSUE THREAD

**Issue by barhom** [peering-manager/docker#5]
When using the included docker-compsoe.yml I am getting the following,

```
Pulling peering-manager-worker (peering-manager:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

```

Any idea why it is saying that the image has been removed?

**Comment by andrew-landsverk-win** [comment]
I noticed you have to change the docker-compose file to read `peeringmanager/peering-manager` in order to pull the images. However, after I fixed that, it says it cannot connect to it's postgres instance. I'm still investigating that on my end.
