### ISSUE TITLE
Templates not found

### ISSUE THREAD

**Issue by natesales** [peering-manager/docker#9]
I have just brought up compose after cloning the repo, and the application seems to be working - I logged into the web UI at :8080 and added an ASN, but clicking on "Import from PeeringDB" under internet exchanges results in a redirect to `:8080/internet-exchanges/peeringdb-import/` and the following error:

```
<class 'peering.models.AutonomousSystem.DoesNotExist'>
AutonomousSystem matching query does not exist.
Python version: 3.9.1
Peering Manager version: v1.3.0
```

Similarly, clicking on "Add a Peering Session" under an AS's Direct Peering Sessions tab results in a redirect to `:8080/direct-peering-sessions/add/?autonomous_system=&return_url=` and error 

```
<class 'django.template.exceptions.TemplateDoesNotExist'>
peering/session/direct/add_edit.html
Python version: 3.9.1
Peering Manager version: v1.3.0
```

Any help would be greatly appreciated!

**Comment by gmazoyer** [comment]
Both issues are not related to the Docker images themselves.

1. Has been addressed in [this commit](https://github.com/peering-manager/peering-manager/commit/94a3a81085b30530e25a7c277f3019af08ef8e45), will be available in next release.

2. Linked to [this issue](https://github.com/peering-manager/peering-manager/issues/346), will be available in next release.
